### ISSUE TITLE
m68k-amigaos-ar fails: "file format not recognized"

### ISSUE THREAD

**Issue by bebbo** [bebbo/amigaos-binutils-2.14#1]
When I do

    m68k-amigaos-ar rs libtest.a obj1.o obj2.o

I get the following error:

    libtest.a: File format not recognized

And the file `libtest.a` is 0 bytes then. It's weird. Why does it even look at `libtest.a`? It should create `libtest.a`, not archive it.

**Comment by bebbo** [comment]
@softwarefailure:

I can run the command above and I can build the libpng.a with the provided files. w/o problem.

Please rebuild you binaries using:
```
make clean
make update
make all
```

**Comment by softwarefailure** [comment]
Ok, seems to be related to the fact that I'm trying to run m68k-amigaos-ar from a NAS device. When I copy the folder to ~ and run m68k-amigaos-ar from there, it works just fine. Trying to archive objects on a NAS device, however, results in the "file format not recognized" error.

**Comment by bebbo** [comment]
I still can't reproduce this issue.

Usually this message indicates that some object has the wrong format

- the library was created using aout lib format
- one object has aout format

reopen if it's reproducable
